name: 'Preview Delete Action'
description: 'Action template for preview request'
author: 'zezaeoh <zezaeoh@github.com>'
inputs:
  application:
    required: true
    description: 'application id (name)'
  branch:
    required: true
    description: 'branch name'
runs:
  using: 'node12'
  main: 'dist/index.js'
